### ISSUE TITLE
Not working on Debian 11 Bullseye x86_64

### ISSUE THREAD

**Issue by lx30011** [userdocs/qbittorrent-nox-static#101]
I'm running a very stock configuration Debian 11 Bullseye VM. I'm experiencing following issues:
- general slowness, much slower than the linuxserver/qbittorrent docker containers for example
- Web UI never loads the torrents, the UI is there, the sidebar shows the right amount of torrents, but the list stays empty

qbittorrent 4.4.5 libtorrent 2.0.7  x86_64-qbittorrent-nox 
`Linux debian 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux`

If you need any additional info reply and I will provide. I'm also able to test using my installation if you have anything in mind.
Thank you

**Comment by userdocs** [comment]
I can replicate the issue and it works fine in WSL2 so i don't think the buidl is the issue.

You'll need to investigate more or use WSL instead of a vm.

**Comment by userdocs** [comment]
Is there anything to add to this?

I'm not sure what can be done without some clear idea of the issue or the what's happening.

**Comment by userdocs** [comment]
closing this for now but feel free to update it if there is more info to add and we can reopen it to resolve anything that highlights.
