### ISSUE TITLE
Version 4.4.5 always downloading errors, not a file permission issue

### ISSUE THREAD

**Issue by dongqiceo** [userdocs/qbittorrent-nox-static#103]
[2.0.8 libbt ](https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-4.4.5_v2.0.8/x86_64-qbittorrent-nox)

**Comment by dongqiceo** [comment]
When I started the error after upgrading this version

**Comment by dongqiceo** [comment]
my system is omv6（debian11）

**Comment by userdocs** [comment]
And it stops if you downgrade?

https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-4.4.5_v2.0.7/x86_64-qbittorrent-nox

**Comment by dongqiceo** [comment]
> And it stops if you downgrade?
> 
> https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-4.4.5_v2.0.7/x86_64-qbittorrent-nox

thanks，ok

**Comment by dongqiceo** [comment]
Interestingly, the old tasks are downloadable

**Comment by dongqiceo** [comment]
maybe problem is init tasks

**Comment by dongqiceo** [comment]
> And it stops if you downgrade?
> 
> https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-4.4.5_v2.0.7/x86_64-qbittorrent-nox

try to downgrade,not work,but i find problem, I set "hashing_threads" to 4, not 1, change back is right
