### ISSUE TITLE
Consider not releasing new binaries into the git repository.

### ISSUE THREAD

**Issue by IceCodeNew** [userdocs/qbittorrent-nox-static#14]
Is there a specific reason for you decided to do so?
This repository is so big while it doesn't make sense.

**Comment by userdocs** [comment]
Seems like a fair point. I can't do much about it now due my attention being required elsewhere.

Contribute via small and relevant pulls and when I get a chance I'll go through them. Most have been good ideas I wish to implement in some.

**Comment by userdocs** [comment]
I think this is mostly resolved.

Just a question of the best method to tag/name the releases.
