### ISSUE TITLE
Allow environment variable to change the source code directory.

### ISSUE THREAD

**Issue by abcfy2** [userdocs/qbittorrent-nox-static#15]
I want to build my own qbittorrent-nox-static(E.g, I modified some codes of qbittorrent locally, and I want to test on my machine. Or I use another qbittorrent fork like qbittorrent enhanced editon).

I hope there are some environment variable could do this.

Like:

```shell
QBITTORRENT_SOURCE_DIR=~/project/qbittorrent OPENSSL_SOURCE_DIR=/usr/src/openssl-1.1.1g ./qbittorrent-nox-static-musl.sh
```

**Comment by userdocs** [comment]
There is currently no way to do what you specifically requested. But i could look into that for a future commit.

Essentially this line is determining the git repo used https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-static-musl.sh#L461

You could just replace this with the URL to your repo. If it is locally sourced then change this https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-static-musl.sh#L463 and comment out the git clone command at line 461

The repor you mentioned has is providing a static build here https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases/tag/release-4.2.5.16

**Comment by abcfy2** [comment]
Thanks.
