### ISSUE TITLE
Use qtlite for reducing size?

### ISSUE THREAD

**Issue by abcfy2** [userdocs/qbittorrent-nox-static#16]
I found qtlite(https://qtlite.com/) is a good way to build a small qt distribution. Would you please use a qtlite config opts for building nox static binary?

**Comment by IceCodeNew** [comment]
> I found qtlite([qtlite.com](https://qtlite.com/)) is a good way to build a small qt distribution. Would you please use a qtlite config opts for building nox static binary?

I think it would be a good idea to bring this idea to the upstream.
我觉得你不妨直接把这个建议提给上游。上游现在至少 Windows 端 MSVC 部分的编译指导我就有在维护，我看那里确实很需要这个优化。

**Comment by userdocs** [comment]
What kind of real world benefit are we looking at here?

Also i don't actually know which modules i should or should not include.

I really need a list of core and optional modules.

**Comment by abcfy2** [comment]
I've found a qt configure option could work, which will reduce nox binary size to 12MB:

```shell
cd qt-everywhere-src-5.15.1/
./configure -recheck-all -opensource -confirm-license -release -static -optimize-size -ltcg -make libs \
  -no-pch -openssl-linked -c++std c++14 -no-opengl -no-dbus -no-widgets -no-gui \
  -no-compile-examples -nomake tests -nomake examples -no-xcb -silent \
  -skip qt3d -skip qtcharts -skip qtgamepad -skip qtwebengine -skip qtnetworkauth \
  -skip qtserialbus -skip qtmultimedia -skip qtscxml -skip qtquick3d -skip qtquicktimeline \
  -skip qtspeech -skip qtlottie -skip qtsensors -skip qtwinextras -skip qtdeclarative \
  -skip qtandroidextras -skip qtscript -skip qtwebchannel -skip qtsvg -skip qtwebsockets \
  -skip qtwebglplugin -skip qtdatavis3d -skip qtremoteobjects -skip qtactiveqt -skip qtwebview \
  -skip qtx11extras -skip qtserialport -skip qtxmlpatterns -skip qtgraphicaleffects -skip qtdoc \
  -skip qtquickcontrols2 -skip qt3d -skip qtimageformats -skip qtconnectivity -skip qtwayland \
  -skip qtquickcontrols -skip qtlocation -skip qtpurchasing \
  -no-feature-testlib
```

**Comment by IceCodeNew** [comment]
> I've found a qt configure option could work, which will reduce nox binary size to 12MB:
> 
> ```shell
> cd qt-everywhere-src-5.15.1/
> ./configure -opensource -confirm-license -release -static -optimize-size -ltcg -make libs \
>   -no-pch -openssl-linked -c++std c++14 -no-opengl -no-dbus -no-widgets -no-gui \
>   -no-compile-examples -nomake tests -nomake examples -no-xcb -silent \
>   -skip qt3d -skip qtcharts -skip qtgamepad -skip qtwebengine -skip qtnetworkauth \
>   -skip qtserialbus -skip qtmultimedia -skip qtscxml -skip qtquick3d -skip qtquicktimeline \
>   -skip qtspeech -skip qtlottie -skip qtsensors -skip qtwinextras -skip qtdeclarative \
>   -skip qtandroidextras -skip qtscript -skip qtwebchannel -skip qtsvg -skip qtwebsockets \
>   -skip qtwebglplugin -skip qtdatavis3d -skip qtremoteobjects -skip qtactiveqt -skip qtwebview \
>   -skip qtx11extras -skip qtserialport -skip qtxmlpatterns -skip qtgraphicaleffects -skip qtdoc \
>   -skip qtquickcontrols2 -skip qt3d -skip qtimageformats -skip qtconnectivity -skip qtwayland \
>   -skip qtquickcontrols -skip qtlocation -skip qtpurchasing \
>   -no-feature-testlib
> ```

Can you be more specific on what Qt modules you had checked to enable on qtlite.com?
你可以详细描述下你在 qtlite.com 站点上选择了开启哪些模块才得到了上面的配置参数吗？
![image](https://user-images.githubusercontent.com/32576256/93971669-4a85ca00-fda3-11ea-9571-1ca19ea3fe32.png)

**Comment by abcfy2** [comment]
> > I've found a qt configure option could work, which will reduce nox binary size to 12MB:
> > 
> >       
> >         
> >       
> >     ```shell
> > cd qt-everywhere-src-5.15.1/
> > ./configure -opensource -confirm-license -release -static -optimize-size -ltcg -make libs \
> >   -no-pch -openssl-linked -c++std c++14 -no-opengl -no-dbus -no-widgets -no-gui \
> >   -no-compile-examples -nomake tests -nomake examples -no-xcb -silent \
> >   -skip qt3d -skip qtcharts -skip qtgamepad -skip qtwebengine -skip qtnetworkauth \
> >   -skip qtserialbus -skip qtmultimedia -skip qtscxml -skip qtquick3d -skip qtquicktimeline \
> >   -skip qtspeech -skip qtlottie -skip qtsensors -skip qtwinextras -skip qtdeclarative \
> >   -skip qtandroidextras -skip qtscript -skip qtwebchannel -skip qtsvg -skip qtwebsockets \
> >   -skip qtwebglplugin -skip qtdatavis3d -skip qtremoteobjects -skip qtactiveqt -skip qtwebview \
> >   -skip qtx11extras -skip qtserialport -skip qtxmlpatterns -skip qtgraphicaleffects -skip qtdoc \
> >   -skip qtquickcontrols2 -skip qt3d -skip qtimageformats -skip qtconnectivity -skip qtwayland \
> >   -skip qtquickcontrols -skip qtlocation -skip qtpurchasing \
> >   -no-feature-testlib
> > ```
> 
> Can you be more specific on what Qt modules you had checked to enable on qtlite.com?
> 你可以详细描述下你在 qtlite.com 站点上选择了开启哪些模块才得到了上面的配置参数吗？
> ![image](https://user-images.githubusercontent.com/32576256/93971669-4a85ca00-fda3-11ea-9571-1ca19ea3fe32.png)

Just use `-skip` option to skip almost all modules, and see: https://github.com/dirtycold/qt-minimal-build/blob/master/qt_minimal-linux-gcc32.configure

**Comment by userdocs** [comment]
1: I use qtbase on github which is a repo size of 70-100 mb

2: This source code package is 554 at minimum http://download.qt.io/official_releases/qt/5.15/5.15.1/single/

Can i do this using the qtbase here https://github.com/qt/qtbase

I am going to try it, but this is the kind of real world outcome vs perceived benefit i am concerned about.

**Comment by abcfy2** [comment]
Sure. I've add these options to my repo: https://github.com/abcfy2/qBittorrent-Enhanced-Edition/blob/ci-testing/.github/workflows/build_and_release.yml#L126

And here is the artifact (with upx): https://github.com/abcfy2/qBittorrent-Enhanced-Edition/releases/tag/v4.2.5.16-3

**Comment by userdocs** [comment]
there seems to be some overlap here and i find it confusing.

Currently I have this 

```
./configure -prefix "$install_dir" -openssl-linked -static -opensource -confirm-license -release -c++std c++14 -no-shared -no-opengl -no-dbus -no-widgets -no-gui -no-compile-examples -I "$include_dir" -L "$lib_dir" QMAKE_LFLAGS="$LDFLAGS"
```

It seems there is a basic requirement for things like `-openssl-linked -static -opensource -confirm-license -release -c++std c++14 -no-shared` but qtbase only has these modules

https://github.com/qt/qtbase/tree/dev/src

There must be a simple way to do this without a command  this long and complicated.

**Comment by abcfy2** [comment]
Seems that the most useful option is `-optimize-size`, and `-static` along with `-no-shared` will cause warning.

`-no-feature-testlib -no-feature-sql` can be safe appending to the configure options.

**Comment by userdocs** [comment]
I have seen the warning, i assume it is becuase `-static` must also set `-no-shared` as the warning is about it being set twice.


Looking at building qt and based on the current script this is what we are working with.

```
Configure summary:
...

Build options:
  Mode ................................... release
  Optimize release build for size ........ yes
  Building shared libraries .............. no
  Using C standard ....................... C11
  Using C++ standard ..................... C++17
  Using ccache ........................... no
  Using new DTAGS ........................ yes
  Relocatable ............................ no
  Using precompiled headers .............. no
  Using LTCG ............................. yes

... 

  Build parts ............................ libs examples tools
Qt modules and options:
  Qt Concurrent .......................... yes
  Qt D-Bus ............................... no
  Qt D-Bus directly linked to libdbus .... no
  Qt Gui ................................. no
  Qt Network ............................. yes
  Qt Sql ................................. yes
  Qt Testlib ............................. yes
  Qt Widgets ............................. no
  Qt Xml ................................. yes
Support enabled for:
  Using pkg-config ....................... yes
  udev ................................... no
  Using system zlib ...................... yes
  Zstandard support ...................... no
Qt Core:
  DoubleConversion ....................... yes
    Using system DoubleConversion ........ no
  GLib ................................... yes
  iconv .................................. no
  ICU .................................... yes
  Built-in copy of the MIME database ..... yes
  Tracing backend ........................ <none>
  Logging backends:
    journald ............................. no
    syslog ............................... no
    slog2 ................................ no
  PCRE2 .................................. yes
    Using system PCRE2 ................... yes
Qt Network:
  getifaddrs() ........................... yes
  IPv6 ifname ............................ yes
  libproxy ............................... no
  Linux AF_NETLINK ....................... yes
  OpenSSL ................................ yes
    Qt directly linked to OpenSSL ........ yes
  OpenSSL 1.1 ............................ yes
  DTLS ................................... yes
  OCSP-stapling .......................... yes
  SCTP ................................... no
  Use system proxies ..................... yes
  GSSAPI ................................. no
Qt Gui:
  Accessibility .......................... yes
  FreeType ............................... yes
    Using system FreeType ................ yes
  HarfBuzz ............................... yes
    Using system HarfBuzz ................ yes
  Fontconfig ............................. yes
  Image formats:
    GIF .................................. yes
    ICO .................................. yes
    JPEG ................................. yes
      Using system libjpeg ............... yes
    PNG .................................. yes
      Using system libpng ................ yes
  Text formats:
    HtmlParser ........................... yes
    CssParser ............................ yes
    OdfWriter ............................ yes
    MarkdownReader ....................... yes
      Using system libmd4c ............... no
    MarkdownWriter ....................... yes
  EGL .................................... no
  OpenVG ................................. no
  OpenGL:
    Desktop OpenGL ....................... yes
    OpenGL ES 2.0 ........................ no
    OpenGL ES 3.0 ........................ no
    OpenGL ES 3.1 ........................ no
    OpenGL ES 3.2 ........................ no
  Vulkan ................................. yes
  Session Management ..................... yes
Features used by QPA backends:
  evdev .................................. yes
  libinput ............................... no
  INTEGRITY HID .......................... no
  mtdev .................................. no
  tslib .................................. no
  xkbcommon .............................. no
  X11 specific:
    XLib ................................. yes
    XCB Xlib ............................. yes
    EGL on X11 ........................... no
    xkbcommon-x11 ........................ no
QPA backends:
  DirectFB ............................... no
  EGLFS .................................. no
  LinuxFB ................................ yes
  VNC .................................... yes
Qt Sql:
  SQL item models ........................ yes
Qt Widgets:
  GTK+ ................................... no
  Styles ................................. Fusion Windows
Qt PrintSupport:
  CUPS ................................... no
Qt Sql Drivers:
  DB2 (IBM) .............................. no
  InterBase .............................. no
  MySql .................................. no
  OCI (Oracle) ........................... no
  ODBC ................................... no
  PostgreSQL ............................. no
  SQLite2 ................................ no
  SQLite ................................. yes
    Using system provided SQLite ......... no
  TDS (Sybase) ........................... no
Qt Testlib:
  Tester for item models ................. yes
```

**Comment by abcfy2** [comment]
`Qt sql` and `Qt Testlib` can be disabled. `-static` might be implied `-no-shared`.

Here is my CI testing: https://github.com/abcfy2/qBittorrent-Enhanced-Edition/runs/1161624553?check_suite_focus=true#step:5:7

You can find the configure options and compiled size from output.

**Comment by userdocs** [comment]
There seems to be another reason for this size reduction.

Using the glibc script, this command you use https://github.com/abcfy2/qBittorrent-Enhanced-Edition/blob/v4_2_x/.github/workflows/build_and_release.yml#L126#L129

does not reduce the binary size of the qt libraries at all.

I am testing this command which is a mix of yours and mine (with some tweaks) and there is no size difference on a glibc system

```
./configure -prefix "$install_dir" -opensource -confirm-license -silent -release -openssl-linked -static -c++std c++14 -optimize-size -ltcg -no-pch -no-dbus -no-gui -no-widgets -no-compile-examples -no-feature-c++17 -no-feature-testlib -no-feature-sql -nomake tests -nomake examples -I "$include_dir" -L "$lib_dir" QMAKE_LFLAGS="$LDFLAGS" 2>&1 | tee "$install_dir/logs/qtbase.log.txt"
```

**Comment by userdocs** [comment]
What are the size of your qt libs after this command completes? https://github.com/abcfy2/qBittorrent-Enhanced-Edition/blob/v4_2_x/.github/workflows/build_and_release.yml#L131

I am struggling to reproduce these results on a glibc system.

**Comment by abcfy2** [comment]
```shell
/usr/local/Qt-5.15.1/lib # du -csh *
167.0K  cmake
17.7M   libQt5Bootstrap.a
1.0K    libQt5Bootstrap.la
1.5K    libQt5Bootstrap.prl
184.0K  libQt5Concurrent.a
1.0K    libQt5Concurrent.la
1.5K    libQt5Concurrent.prl
48.8M   libQt5Core.a
1.0K    libQt5Core.la
1.5K    libQt5Core.prl
21.5M   libQt5Network.a
1.0K    libQt5Network.la
1.5K    libQt5Network.prl
1.8M    libQt5Xml.a
1.0K    libQt5Xml.la
1.5K    libQt5Xml.prl
1.9M    libqtpcre2.a
1.0K    libqtpcre2.prl
351.5K  metatypes
6.0K    pkgconfig
92.5M   total
```

**Comment by userdocs** [comment]
I ma wondering if the size reduction is related to other static components you installed using apk instead of build.

**Comment by abcfy2** [comment]
No. You can find the old release here: https://github.com/abcfy2/qBittorrent-Enhanced-Edition/releases/tag/v4.2.16-3

Without `-optimize-size`, the release size is about 40MB+ (20 MB after upx compressing).

**Comment by userdocs** [comment]
Which is what i can replicate when my command also used optimise size and my lib sizes are pretty much the same.

**Comment by abcfy2** [comment]
Maybe you can use these options: https://github.com/abcfy2/qBittorrent-Enhanced-Edition/blob/ci-testing/.github/workflows/build_and_release.yml#L126

**Comment by userdocs** [comment]
It's not making any difference.

```
./configure -prefix "$install_dir" -opensource -confirm-license -silent -release -openssl-linked -static -c++std c++14 -optimize-size -ltcg -make libs -no-pch -no-opengl -no-dbus -no-gui -no-widgets -no-compile-examples -no-feature-c++17 -no-feature-testlib -no-feature-sql -nomake tests -nomake examples -no-xcb'
```

The outcome.

```
18M     libQt5Bootstrap.a
4.0K    libQt5Bootstrap.la
4.0K    libQt5Bootstrap.prl
188K    libQt5Concurrent.a
4.0K    libQt5Concurrent.la
4.0K    libQt5Concurrent.prl
49M     libQt5Core.a
4.0K    libQt5Core.la
4.0K    libQt5Core.prl
23M     libQt5Network.a
4.0K    libQt5Network.la
4.0K    libQt5Network.prl
1.9M    libQt5Xml.a
4.0K    libQt5Xml.la
4.0K    libQt5Xml.prl
91M     total
```

My final qbitorrent-nox size is till 49M

If you can replicate your result with my script, by all means, otherwise i think the change is related to another part of the process.

**Comment by abcfy2** [comment]
Maybe just remove `ICU` ?

I find `ICU` is not the required dependency.

**Comment by userdocs** [comment]
I think icu was part of building boost. It looks like you install boost libs and not compile them.

I think this is where the projects diverge. My build is not about upx  or size optimisation. It is about building without Installing anything other than standard safe dependencies.

I will test if I can skip icu though.

**Comment by abcfy2** [comment]
Yes, `skip_icu='yes'` will reduce the size to 17MB.

**Comment by userdocs** [comment]
I dont actually know if there is a benefit to having icu. It was just part of the original build process to get through warning and compilation issues.

**Comment by userdocs** [comment]
Ok, so i have done some testing and needed some input so i asked a question here https://qbforums.shiki.hu/viewforum.php?f=15

It needs to be approved but the title is `Qbittorrent and ICU libraries` so it should be obvious to see once it is.

The main conclusion and issue i have is how ICU is automatically included in the build process if the `libicu-dev` package is present.

If you at any time install this package the binary size will return to 50M and i am unsure exactly where or how this is decided. (which dependency) So it appears there is a automated preference to include and use this library and the forum post i linked should help to understand this before i can just not use ICU.

Look at this example when building with the staticish script.

Staticish with libicu-dev

```
linux-vdso.so.1 (0x00007ffc2888a000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7335992000)
libicui18n.so.63 => /lib/x86_64-linux-gnu/libicui18n.so.63 (0x00007f73356b7000)
libicuuc.so.63 => /lib/x86_64-linux-gnu/libicuuc.so.63 (0x00007f73354e8000)
libicudata.so.63 => /lib/x86_64-linux-gnu/libicudata.so.63 (0x00007f7333af8000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7333af3000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f733396f000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f73337ea000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f73337d0000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f733360f000)
/lib64/ld-linux-x86-64.so.2 (0x00007f7336ce2000)
```

Staticish with without libicu-dev

```
linux-vdso.so.1 (0x00007ffcc855f000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd78831e000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd788319000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd788195000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd788012000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd787ff8000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd787e37000)
/lib64/ld-linux-x86-64.so.2 (0x00007fd7896e5000)
```

I am trying to determine now which part of the build is including it.

**Comment by userdocs** [comment]
this all comes down to using `-no-icu` due to this check:

https://github.com/qt/qtbase/blob/9c5698a8fcf9b890d8ed23b8e6cbab2971c8dc87/config_help.txt#L247

I don't think there is anything else to it. skip ICU or use that argument and you get the smaller size.

**Comment by userdocs** [comment]
After this thread https://github.com/qbittorrent/qBittorrent/issues/13457 i think i'm going to skip ICU by default but leave the code for now. Ill add a flag to turn it on.
