### ISSUE TITLE
Testing: merged pull reqests into qbittorrent-nox-staticish-mk2.sh

### ISSUE THREAD

**Issue by userdocs** [userdocs/qbittorrent-nox-static#17]
@IceCodeNew please take a look at this script

https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-staticish-mk2.sh

I have added most of the ideas you presented but in slightly different ways,

### Contributor credit

https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-staticish-mk2.sh#L9

Since the pull requests are closed and have overlapping i'll credit you this way? 

### Download and delete functions 

https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-staticish-mk2.sh#L245#L294

This is what i wanted to do before merging the ideas. Now there are two functions to manage instead of many commands. They are here now making relevant changes is easier.

### better git commands, why?

I tested this and in the default mode where boost was downloaded from bintray the overall transfer of the script was 230M and the git commands make little difference. The problem occurred when this boost archive was unavailable and the script defaulted to boost from github. it then became 1250M. Using the the better boost commands the transfer is consistently 230M with either method but may take longer to complete when downloading boost from github.

### curl flags 

https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-staticish-mk2.sh#L244

I have only used to for the main functions and not he url variables for now. but this is the idea.

### proxy support

No system modifications. Specific to the script

https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-staticish-mk2.sh#L49#L51
https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-staticish-mk2.sh#L244
https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-staticish-mk2.sh#L266

### new flag 

https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-staticish-mk2.sh#L45

This is to use the qbittorrent master and/or libtorrent main branch (RC_1_2) when building.

### Testing

Try it out and let me know if it manages to merged the changes you were contributing.

**Comment by IceCodeNew** [comment]
Thanks for your work!

**Comment by IceCodeNew** [comment]
> ### curl flags
> [https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-staticish-mk2.sh#L244](https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-staticish-mk2.sh?rgh-link-date=2020-10-01T21%3A24%3A25Z#L244)
> 
> I have only used to for the main functions and not he url variables for now. but this is the idea.

This idea actually works, though I'd suggest introducing `curl` as a function, like this:
```shell
curl() {
  $(type -P curl) -sSLNq --connect-timeout 5 --retry 5 --retry-delay 10 --retry-max-time 60 ${CURL_PROXY} "$@"
}
```

**Comment by IceCodeNew** [comment]
> The problem occurred when this boost archive was unavailable and the script defaulted to boost from github. it then became 1250M. Using the the better boost commands the transfer is consistently 230M with either method but may take longer to complete when downloading boost from github.

Cool.

**Comment by userdocs** [comment]
Ok so i merged and  pushed some changes.

**Comment by userdocs** [comment]
ok, everything is now updated and pushed. closed but not locked.
