### ISSUE TITLE
script musl hangs after Installing boost build

### ISSUE THREAD

**Issue by nephaste** [userdocs/qbittorrent-nox-static#2]
Hi thanks a lot for this scripts

i installed an LXC Alpine 3.11 amd64 to statically build with musl script

after adding bash and tar missing in base configuration i am starting script

./qbittorrent-nox-static-musl.sh all

all runs fine but script hangs after 

`
Installing boost build

Bootstrapping the build engine with toolset gcc...

Bootstrapping is done. To build and install, run:

    ./b2 install --prefix=<DIR>

warning: No toolsets are configured.
warning: Configuring default toolset "gcc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
...found 471 targets...
...updating 239 targets...
common.copy /root/qbittorrent-build/bin/b2
common.copy /root/qbittorrent-build/share/boost-build/boost-build.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build-system.jam
common.copy /root/qbittorrent-build/share/boost-build/src/tools/cygwin.jam
common.copy /root/qbittorrent-build/share/boost-build/src/tools/cw.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/virtual-target.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/version.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/type.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/toolset.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/targets.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/scanner.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/property.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/property-set.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/project.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/feature.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/generators.jam
common.copy /root/qbittorrent-build/share/boost-build/src/build/configure.jam
.....

common.copy /root/qbittorrent-build/share/boost-build/src/util/regex.jam
common.copy /root/qbittorrent-build/share/boost-build/src/util/param.jam
common.copy /root/qbittorrent-build/share/boost-build/src/util/print.jam
common.copy /root/qbittorrent-build/share/boost-build/src/util/path.jam
common.copy /root/qbittorrent-build/share/boost-build/src/util/os.jam
common.copy /root/qbittorrent-build/share/boost-build/src/util/order.jam
common.copy /root/qbittorrent-build/share/boost-build/src/util/option.jam
common.copy /root/qbittorrent-build/share/boost-build/src/util/numbers.jam
common.copy /root/qbittorrent-build/share/boost-build/src/util/indirect.jam
common.copy /root/qbittorrent-build/share/boost-build/src/util/doc.jam
common.copy /root/qbittorrent-build/share/boost-build/src/util/container.jam
common.copy /root/qbittorrent-build/share/boost-build/src/util/assert.jam
common.copy /root/qbittorrent-build/share/boost-build/src/kernel/modules.jam
common.copy /root/qbittorrent-build/share/boost-build/src/kernel/errors.jam
common.copy /root/qbittorrent-build/share/boost-build/src/kernel/class.jam
common.copy /root/qbittorrent-build/share/boost-build/src/kernel/bootstrap.jam
common.copy /root/qbittorrent-build/share/boost-build/src/kernel/boost-build.jam
...updated 239 targets...

Installing boost libraries
`

and nothing more.... got prompt just like it was finnished

have any clue how to fix this ? 

looking inside qbittorrent-build .. all files were deleted and only have a boost.tar.gz 0KB ...

sames happen on ARM64 LXC ...

**Comment by userdocs** [comment]
what provider are you using?

**Comment by nephaste** [comment]
provider ?

LXC is based on a Qnap NAS (container station)... I built previously  4.2.1 without any problem on your script (Alpine 3.10), but i upgraded to Alpine 3.11 my container .. and restarted from scratch ... due QBittorrent updated to 4.2.2 ...

I am the QnapClub QPKG maintainer for QBitorrent and i ma using your script to propose this applicaton to Qnap Community

https://www.qnapclub.eu/fr/qpkg/358

**Comment by userdocs** [comment]
I build on scaleway. I will fire up an instance now and test. I'll see if there is a problem.

**Comment by nephaste** [comment]
thanks

**Comment by userdocs** [comment]
This appears to be the problems. Forbidden.

https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz

From here. all links here appear broken.

https://www.boost.org/users/download/

can you confirm?

**Comment by nephaste** [comment]
mmmmm good catch

indeed : https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2

forbidden

**Comment by nephaste** [comment]
may be can move to github directly

https://github.com/boostorg/boost/releases

**Comment by userdocs** [comment]
If I remember in did this but it takes a considerable time to pull all modules. It is possible but maybe add 50% time to the build process

**Comment by userdocs** [comment]
i'll look into the github method but for the mean time this is the issue.

https://github.com/boostorg/boost/issues/384

**Comment by nephaste** [comment]
thank again... i will test within 2 days

**Comment by userdocs** [comment]
if you want i can make a version with boost from github you can use now? it will take a bit longer to build.

**Comment by userdocs** [comment]
Here is a working script using github for boost instead.

https://gist.github.com/userdocs/59801f3a394086309dd916129796fe07

I am undecided if i will make this the default method. I'll think about it over the next few days.

**Comment by nephaste** [comment]
Works Like a charm.. thanks a lot

AMD64 , ARM64, ARMV7 and i686 BUILT without any issue

**Comment by userdocs** [comment]
Thanks for the update. When I decide how to proceed I'll update close the ticket.

**Comment by nephaste** [comment]
no problem... and thanks again ...
Hope to see more great script like this one for other apps ...

**Comment by userdocs** [comment]
I also have this https://github.com/userdocs/lftp-static

I have pushed the changes for the Muslim script to use github for boost

**Comment by nephaste** [comment]
think Qnap users are more looking for entertainment things or backup server purpose

like Amule , TransmissionBT...,  or UrBackup, Bareos ...

**Comment by userdocs** [comment]
boost is now pulled from github
