### ISSUE TITLE
v4.3.0.1

### ISSUE THREAD

**Issue by kaputeko** [userdocs/qbittorrent-nox-static#20]
Thank you for your work.

Do you intend to port the latest version v4.3.0.1?

**Comment by userdocs** [comment]
This script is for building qbittorrent  -nox on linux. v4.3.0.1 is a specific fix for windows versions. I could do it but I didnt see the need to do it.

**Comment by kaputeko** [comment]
I'm sorry.
I thought if the update was for Linux too.
Wonderful, I'll already upgrade it.
Thanks!
