### ISSUE TITLE
Allow applying libtorrent patches before build

### ISSUE THREAD

**Issue by darthShadow** [userdocs/qbittorrent-nox-static#25]
I wanted to have the option to apply a custom patch to libtorrent before it's built, similar to the option available in [swizzin](https://github.com/swizzin/swizzin/blob/0ad168451af17ae6a396d09f1f9f6cedd50212b4/sources/functions/libtorrent#L315).

Preferably, a custom patch folder containing multiple patches could also be specified instead of only allowing a single patch.

**Comment by userdocs** [comment]
It's a possibility. The current patch function is more specific to the boost jamfiles rather than patching libtorrent. 

The patch code you mention is this https://github.com/swizzin/swizzin/blob/master/sources/functions/libtorrent#L315-L318

You can test it an see if it works.

**Comment by darthShadow** [comment]
Yep, that works if I copy-paste that part into the install script but if you want me to send it as a PR, then, unfortunately, I am not as comfortable with bash so as to create a flag for specifying the folder with proper checks and loop on it.

**Comment by userdocs** [comment]
ok, i have added this section https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-static.sh#L409-L426

and added a `-bs / --boot-strap` flag to open to door to this.

If you can explain to me what you need to do and why, how many files, what files. i will look to see if i can expand this patch function to allow for that by using `-bs` or from a  repo.

**Comment by darthShadow** [comment]
I was thinking of patches like this:

* https://github.com/horjulf/docker-qbittorrent/blob/master/patches/qbittorrent_settings_pack.patch (for qbittorrent)
* https://github.com/swizzin/swizzin/blob/master/sources/functions/libtorrent#L306-L312 (for libtorrent)

Ideally, we could specify a separate patch folder for both and the script could just iterate over the files present in both and apply them one by one.

**Comment by userdocs** [comment]
ok, i'll probably add this so i'll leave the issue open until it's done.

**Comment by userdocs** [comment]
You can try this.

https://github.com/userdocs/qbittorrent-nox-static/pull/28

**Comment by darthShadow** [comment]
Thanks a lot for the quick turnaround. Seems to be working nicely.

One small enhancement that could be done is to make the bootstrap function create the patch directories according to the defaults instead of making it static. In that case, any future default changes can be done in a single place rather than in multiple places.

**Comment by userdocs** [comment]
I've add that/ But when it comes to patching, i'm only providing generic folders matched against tags.

`4.3.*` will create the folder `430`. It's either this or a folder per github tag, which i think it too much.

The end user needs to manage their patches, preferably via github, and the bootstrap is more a on a  generic guidance non hosted patches, which are automated.

**Comment by darthShadow** [comment]
Yeah, I noticed that regex. Seems perfectly reasonable to me and a good compromise between too little or too much in options.

**Comment by userdocs** [comment]
I have made some changes and i think that is about it.

### bootstrap:

The dir format is now `build_dir/patch/appname/tag/patch`. Tags are now more specific and abbreviated from the main tag.

`libtorrent-1_2_11` becomes `1.2.11`
`v1.2.11` becomes `1.2.11`
`RC_1_2` stays as `RC_1_2`
`release-4.3.1` becomes `4.3.1`

### automated

git url format is 

```
https://raw.githubusercontent.com/username/repo/master/patches/appname/tag/patch
```

In your repo you just need to emulate this part

```
patches/appname/tag/patch
```

For example

```
patches/libtorrent/1.2.11/patch
patches/qbittorrent/4.3.1/patch
```

tags need to be a valid abbreviated tag.

You can trigger this automated patching in 2 ways using your username and repo.

hardcode `patches_url="username/repo"` in the script

provide the flag and arguments `-pr username/repo`

I've added a few unrelated things but they are not part of this particular thing.

**Comment by darthShadow** [comment]
Looks good, thanks a lot again.
