### ISSUE TITLE
Setting build-directory doesn't work anymore

### ISSUE THREAD

**Issue by darthShadow** [userdocs/qbittorrent-nox-static#26]
The path set either `-b` or `--build-directory` is no longer used and it always defaults to `qbittorrent-build` in the current directory.

---

Related code: https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-static.sh#L556-L566

```bash
set_build_directory # see functions
#
set_module_urls # see functions
#####################################################################################################################################################
# This section controls our flags that we can pass to the script to modify some variables and behavior.
#####################################################################################################################################################
while (("${#}")); do
	case "${1}" in
		-b | --build-directory)
			qb_build_dir="${2}"
			shift 2
```

My understanding from the code is that since the function `set_build_directory` is called before the arguments are parsed, then any value set by the arguments is not used.

**Comment by userdocs** [comment]
what is your command because it works for me.

**Comment by darthShadow** [comment]
`./qbittorrent-nox-static.sh all --icu --build-directory "build"`

**Comment by userdocs** [comment]
That command works, but maybe you are looking in the wrong place?

`./qbittorrent-nox-static.sh -h-b`

`--build-directory build` will create a the directly `build` directory relative to the scripts location.

``--build-directory ~/build` will create a the directly `build` directory at the top level `/build`

``--build-directory /build` will create a the directly `build` directory in your home dir.

So is the build dir in the same location as your script?

**Comment by userdocs** [comment]
sorry, i made some confusing typos i fixed.

**Comment by darthShadow** [comment]
No, it doesn't. It completely ignores it and uses the default `qbittorrent-build` directory relative to the script location.

The code also implies the same since it sets the `install_dir` before the arguments ever get processed. Am I reading that wrong in the code?

**Comment by userdocs** [comment]
Yes, sorry, i was using a local version where i had this fixed but had not pushed the change. It should be fixed now with this https://github.com/userdocs/qbittorrent-nox-static/commit/b8e7400b5dd16cda4cfd39383ce3409fd20dc4ad

**Comment by darthShadow** [comment]
It's working fine now, thanks. One minor enhancement is that you could update the value of `qb_install_dir_short` in the `set_build_directory`, otherwise, it builds to the correct location but prints the default location for all statements

**Comment by userdocs** [comment]
that should also be fixed now, thanks for letting me know.

**Comment by darthShadow** [comment]
Great, thanks for the help.
