### ISSUE TITLE
Release old version of qBittorrent

### ISSUE THREAD

**Issue by pd12bbf7608ae1** [userdocs/qbittorrent-nox-static#30]
Some of my private trackers have banned qBittorrent v4.3.x, and I cannot install old version of qBittorrent from official PPAs.

Can you build some old release such as qBittorrent v4.1.9.1 and put it to release?

Thanks.

**Comment by userdocs** [comment]
The script support custom tags but no promise they combo works.

use the -h option. 

-qt release-4.1.9.1 -lt libtorrent-1_1_14
