### ISSUE TITLE
4.2.5.1.2.10 version release does not meet

### ISSUE THREAD

**Issue by Latezly** [userdocs/qbittorrent-nox-static#33]
https://github.com/userdocs/qbittorrent-nox-static/releases/tag/4.2.5.1.2.10

```
wget https://github.com/userdocs/qbittorrent-nox-static/releases/download/4.2.5.1.2.10/amd64-glibc-qbittorrent-nox
~ # chmod +x amd64-glibc-qbittorrent-nox 
~ # ./amd64-glibc-qbittorrent-nox --version
qBittorrent v4.3.0alpha1
```

**Comment by userdocs** [comment]
Should be fixed. Try now.

**Comment by Latezly** [comment]
OK now his version is correct
However, I noticed that I used the version compiled without icu, and the volume is about 20MB
Have you considered adding a version without icu?

**Comment by userdocs** [comment]
I don't consider the ICU an issue.

You can use the build script to make a custom version.
