### ISSUE TITLE
Boost module not installing

### ISSUE THREAD

**Issue by joshft91** [userdocs/qbittorrent-nox-static#37]
Hello!

I stumbled across your repo in search of an easier way to get a newer version of qBittorrent on a Raspberry Pi 4B (using OS lite, headless). I'm fairly new Linux in general, but I think I came across an issue trying to create a new `qbittorrent-nox` binary. I believe Pi OS Lite is based on Debian.

I started the script with everything by default: `./qbittorrent-nox-static.sh all`

This ran completely fine for quite a while until it got to the `boost` installation and I get the below error.

```
Installing boost
./qbittorrent-nox-static.sh: line 277: : command not found
 There is an issue with your proxy settings or network connection
```

I isolated the issue by running `./qbittorrent-nox-static.sh boost` where I can see the other modules skip installation because they were successful, but get the same problem above. It looks like it's failing to get the status of the boost module/version from their git repo, but I'm not quite familiar enough with the script to have it nailed down yet.

Let me know any other information you might need to help debug this issue. Thanks!

**Comment by userdocs** [comment]
do you have git installed on the pi?

```
apt-get install git
```

**Comment by joshft91** [comment]
Womp womp. I'm an idiot... that was definitely the issue, I hadn't even considered that git wouldn't come with Pi OS. Cheers

**Comment by userdocs** [comment]
Two things.

1: I am not sure why the setup continued without git as it is a required package, was everything green with no got installed?

2: On a successful build you may encounter this issue https://github.com/userdocs/qbittorrent-nox-static/issues/29

**Comment by joshft91** [comment]
1. The only thing I noticed right away that something was off was I got a few `./qbittorrent-nox-static.sh: line 277: : command not found` message (maybe 5 or so)... but the script just kept running until installing the boost module. Then it completely died.
2. Will do, I'll see if I have any issues with that. Thank you
