### ISSUE TITLE
Pi 4, can't compile/produce qbittorrent-nox binary

### ISSUE THREAD

**Issue by joshft91** [userdocs/qbittorrent-nox-static#38]
Apologies for writing another issue already, I seem to be having an issue at the very end of attempting to produce the actual `qbittorrent-nox` file.

Current process:
1. Ran `./qbittorrent-nox-static.sh all`
    - Appeared to work fine all the way to the last step when attempting to compile/build qbittorrent
    - No `qbittorrent-nox` file was produced in `/qb-build/bin`
2. Restarted the Pi 4
    - Ran `./qbittorrent-nox-static.sh all` again to ensure nothing was weird after installing dependencies previously
    - Encountered same issue described below
3. Ran `./qbittorrent-nox-static.sh boost` (required to build qbittorrent-nox since [it gets deleted](https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-static.sh#L1243) after running the qbittorrent module)
4. Ran ./qbittorrent-nox.static.sh qbittorrent` 
    - Works fine until the following logs are produced below
 5. No binary produced

It appears to be something around potentially not finding the `-l:libtorrent.a` file? Continuing to try a couple things but wanted to see if this error is anything you've seen before. Cheers.

```
linking qbittorrent-nox
/usr/bin/ld: cannot find -l:libtorrent.a
/usr/bin/ld: /home/pi/qbittorrent-playground/qb-build/lib/libQt5Core.a(qlibrary_unix.o): in function `QLibraryPrivate::load_sys()':
qlibrary_unix.cpp:(.text._ZN15QLibraryPrivate8load_sysEv+0x5e8): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /home/pi/qbittorrent-playground/qb-build/lib/libQt5Core.a(qfilesystemengine_unix.o): in function `QFileSystemEngine::resolveGroupName(unsigned int)':
qfilesystemengine_unix.cpp:(.text._ZN17QFileSystemEngine16resolveGroupNameEj+0x158): warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /home/pi/qbittorrent-playground/qb-build/lib/libQt5Core.a(qfilesystemengine_unix.o): in function `QFileSystemEngine::resolveUserName(unsigned int)':
qfilesystemengine_unix.cpp:(.text._ZN17QFileSystemEngine15resolveUserNameEj+0x5c): warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /home/pi/qbittorrent-playground/qb-build/lib/libcrypto.a(b_addr.o): in function `BIO_lookup_ex':
b_addr.c:(.text+0xad4): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /home/pi/qbittorrent-playground/qb-build/lib/libcrypto.a(b_sock.o): in function `BIO_gethostbyname':
b_sock.c:(.text+0x4c): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:616: qbittorrent-nox] Error 1
make[1]: Leaving directory '/home/pi/qbittorrent-playground/qb-build/qbittorrent/src'
make: *** [Makefile:47: sub-src-make_first] Error 2
cd src/ && ( test -e Makefile || /home/pi/qbittorrent-playground/qb-build/bin/qmake -o Makefile /home/pi/qbittorrent-playground/qb-build/qbittorrent/src/src.pro QMAKE_LRELEASE= ) && make -f Makefile install
make[1]: Entering directory '/home/pi/qbittorrent-playground/qb-build/qbittorrent/src'
linking qbittorrent-nox
/usr/bin/ld: cannot find -l:libtorrent.a
/usr/bin/ld: /home/pi/qbittorrent-playground/qb-build/lib/libQt5Core.a(qlibrary_unix.o): in function `QLibraryPrivate::load_sys()':
qlibrary_unix.cpp:(.text._ZN15QLibraryPrivate8load_sysEv+0x5e8): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /home/pi/qbittorrent-playground/qb-build/lib/libQt5Core.a(qfilesystemengine_unix.o): in function `QFileSystemEngine::resolveGroupName(unsigned int)':
qfilesystemengine_unix.cpp:(.text._ZN17QFileSystemEngine16resolveGroupNameEj+0x158): warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /home/pi/qbittorrent-playground/qb-build/lib/libQt5Core.a(qfilesystemengine_unix.o): in function `QFileSystemEngine::resolveUserName(unsigned int)':
qfilesystemengine_unix.cpp:(.text._ZN17QFileSystemEngine15resolveUserNameEj+0x5c): warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /home/pi/qbittorrent-playground/qb-build/lib/libcrypto.a(b_addr.o): in function `BIO_lookup_ex':
b_addr.c:(.text+0xad4): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /home/pi/qbittorrent-playground/qb-build/lib/libcrypto.a(b_sock.o): in function `BIO_gethostbyname':
b_sock.c:(.text+0x4c): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:616: qbittorrent-nox] Error 1
make[1]: Leaving directory '/home/pi/qbittorrent-playground/qb-build/qbittorrent/src'
make: *** [Makefile:59: sub-src-install_subtargets] Error 2
```

**Comment by userdocs** [comment]
What you should do it delete the build folder and start again.

```
./qbittorrent-nox-static.sh all
```

After you can look at the build logs in `qb-build/logs` to see what build failed.

**Comment by joshft91** [comment]
Thanks, I'll get back to you; need to set up my Pi4 after it crashed due to something else this morning. Will see if a clean install will fix the problem I was encountering.

**Comment by joshft91** [comment]
Alright, it seems to be some sort of libtorrent compile/build issue that I'm running into. I noticed that when doing the libtorrent module that at one point it will freeze for quite a while, and then I get this error: `g++: fatal error: Killed signal terminated program cc1plus`

Seems that the more specific error is this:
`...failed gcc.compile.c++ bin/gcc-8/release/address-model-32/crypto-openssl/cxxstd-17-iso/link-static/threading-multi/src/session_impl.o...`

The last few lines of `libtorrent.log.txt` are here:
```
...skipped <pbin/gcc-8/release/address-model-32/crypto-openssl/cxxstd-17-iso/link-static/threading-multi>libtorrent.a(clean) for lack of <pbin/gcc-8/release/address-model-32/crypto-openssl/cxxstd-17-iso/link-static/threading-multi>src/session_impl.o...
...skipped <pbin/gcc-8/release/address-model-32/crypto-openssl/cxxstd-17-iso/link-static/threading-multi>libtorrent.a for lack of <pbin/gcc-8/release/address-model-32/crypto-openssl/cxxstd-17-iso/link-static/threading-multi>src/session_impl.o...
...skipped <p/home/pi/qbittorrent-playground/qb-build/lib>libtorrent.a for lack of <pbin/gcc-8/release/address-model-32/crypto-openssl/cxxstd-17-iso/link-static/threading-multi>libtorrent.a...
...failed updating 1 target...
...skipped 3 targets...
...updated 434 targets..
```

Which lines up with the issue seen when attempting to build `qbittorrent`
```
linking qbittorrent-nox
/usr/bin/ld: cannot find -l:libtorrent.a
```

Not sure why I wouldn't be able to compile/build, seems like everything else is okay.

**Comment by userdocs** [comment]
it hard for me to help since I don't have a pie and it's a 32 bit os.

I am not sure where the problem is it may be the same error as here

https://github.com/arvidn/libtorrent/issues/5117

**Comment by joshft91** [comment]
No problem, thanks for at least reading. I'll close this out since it does appear to be something OS/32-bit related. I'll dig into building libtorrent and see if I can go from there. Thanks

**Comment by joshft91** [comment]
I finally got the latest version of qBittorrent (4.3.3) built after working through the issues I was encountering above. Turns out it was due to Out of Memory issues when building libtorrent. I've outlined the way I solved the problem below. Thanks @userdocs for the responses along the way.

Hardware: `Raspberry Pi 4 2GB`
OS: [`Raspberry Pi OS 64-bit`](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2020-08-24/)

Problem: `./qbittorrent-nox-static.sh` dies when attempting to build the libtorrent module
Fix: Create a 1Gb swapfile according [to these instructions](https://www.raspberrypi.org/forums/viewtopic.php?t=142243) and attempt to build libtorrent again.

Libtorrent was then created successfully allowing me to then run `./qbittorrent-nox-static.sh qbittorrent` and get the `qbittorrent-nox` binary.

**Comment by userdocs** [comment]
That is good to know, thanks. 

Does the binary run with no issues?

**Comment by joshft91** [comment]
It did, yep. No issues or anything, I just executed the binary and it started with no problem on port 8080. I suspect that there's not a lot of Pi4 2GB models out there that people are building ... it looks like even with 4GB it would have no problem.
