### ISSUE TITLE
Can I run a specific version of this?

### ISSUE THREAD

**Issue by FatSandwich** [userdocs/qbittorrent-nox-static#39]

**Comment by userdocs** [comment]
You mean a specific version of that?

**Comment by FatSandwich** [comment]
A specific version of qbittorrent-nox

**Comment by userdocs** [comment]
The built in switches show and explain their options. https://github.com/userdocs/qbittorrent-nox-static#flags-and-arguments-summarised

In theory you can build any version of qbittorrent with any version of libtorrent. The script won't stop you. In reality you need to build against the conditions defined by qbittorrent. For example.

https://www.qbittorrent.org/news.php for v4.3.4.1 says that:

```
OTHER: Raise minimum libtorrent version to 1.2.12 (glassez)
OTHER: Raise minimum Qt version to 5.12 (glassez)
```

So you can only go back as far as 1.2.12

I don't really support older versions. So if an older version build fails i'm not going to try to fix it. As long ag the versions support each other it will probably work.

The command looks like this to specify a non default version of either.

```
./qbittorrent-nox-static.sh all -qt release-4.3.3 -lt 1.2.10
```
