### ISSUE TITLE
About GeoIP

### ISSUE THREAD

**Issue by SKIYET** [userdocs/qbittorrent-nox-static#4]
Dear

I made the static build of qb with your scrpit, but the country resolving function does not work.
The database has been used as this guide “https://github.com/qbittorrent/qBittorrent/wiki/How-to-use-MaxMind's-GeoIP-database”.
But the country resolving function seemed still not work.

I  found the libmaxminddb is not installed in your script.
Maybe  the issed is caused by libmaxminddb .

**Comment by userdocs** [comment]
This is how the database is added and used. 

https://github.com/qbittorrent/qBittorrent/blob/master/src/base/net/geoipmanager.cpp#L45

**Comment by SKIYET** [comment]
Thanks
