### ISSUE TITLE
Opensuse?

### ISSUE THREAD

**Issue by mgaulton** [userdocs/qbittorrent-nox-static#40]
I need something like this in my life, any chance you have or could point me to similar that would work on Opensuse Tumbleweed? Their repo builds aren't working for me any longer due to compile issues.

**Comment by userdocs** [comment]
The releases are statically complied so having compiled issues with them does not make much sense.

Without clarification i don't  really understand your issue.

**Comment by mgaulton** [comment]
Apologies.
I'm currently having issues with the rpms on the reports for Opensuse
Tumbleweed. (not your issue, just background)
I would like to use your script, but don't think I can in the current state
as the distro is rpm based.
I was wondering if you'd looked at making an rpm version to do this build
script as well?

Thanks

**Comment by userdocs** [comment]
the static builds in the release will work on your distro. use the musl one. 

You can build in an alpine or debian based docker on your platform if you need custom settings.

I don't use an rpm based system so i have no plans to add support.

**Comment by mgaulton** [comment]
Awesome. Thanks for the info. Its appreciated.

**Comment by userdocs** [comment]
Did the static binary work for you on OpenSuse?

**Comment by mgaulton** [comment]
i did but threw me some errors but the UI loaded.

```server6:~/bin # ./qbittorrent-nox
The legacy data directory '/root/.local/share/data/qBittorrent/' is used.
It is recommended to move its content to '/root/.local/share/qBittorrent/'
The legacy data directory '/root/.local/share/data/qBittorrent/' is used.
It is recommended to move its content to '/root/.local/share/qBittorrent/'
The legacy data directory '/root/.local/share/data/qBittorrent/' is used.
It is recommended to move its content to '/root/.local/share/qBittorrent/'
The legacy data directory '/root/.local/share/data/qBittorrent/' is used.
It is recommended to move its content to '/root/.local/share/qBittorrent/'
The legacy data directory '/root/.local/share/data/qBittorrent/' is used.
It is recommended to move its content to '/root/.local/share/qBittorrent/'

******** Information ********
To control qBittorrent, access the Web UI at http://localhost:8080
bool Http::RequestParser::parsePostMessage(const QByteArray&) unknown
content type: "text/xml"
Http::RequestParser::ParseResult Http::RequestParser::doParse(const
QByteArray&) message body parsing error
bool Http::RequestParser::parsePostMessage(const QByteArray&) unknown
content type: "text/xml"
Http::RequestParser::ParseResult Http::RequestParser::doParse(const
QByteArray&) message body parsing error
```

**Comment by userdocs** [comment]
That build uses ICU. Maybe it will work in a build without it. I am not sure exactly what the error is though

**Comment by mgaulton** [comment]
Seems to be stable so far. I'll let you know if I figure anything out.
