### ISSUE TITLE
Changing the web iu css

### ISSUE THREAD

**Issue by natbrood** [userdocs/qbittorrent-nox-static#44]
Where can I find the Layout.css that it uses to render the webpage?  I can't seem to find it

**Comment by userdocs** [comment]
if you can explain what you are trying to do it would help get a better answer.

**Comment by natbrood** [comment]
My goal is not to burn my eyes at night. I usually use a browser extension for this. But it would be useful to edit the css to add a dark theme

**Comment by userdocs** [comment]
Probably this

https://github.com/qbittorrent/qBittorrent/tree/master/src/webui/www/private/css

You can use the patch method

https://userdocs.github.io/qbittorrent-nox-static/#/patching

Or try this

https://github.com/repslet/nightwalker
