### ISSUE TITLE
So many types, so which one I shall use?

### ISSUE THREAD

**Issue by alexyw** [userdocs/qbittorrent-nox-static#48]
My compute is x86_64, I am using Debian 10.
I see a lot of qb release files, such as ***icu***.  for now , I download "x86_64-qbittorrent-nox", but in the readme file, it tells me the " x86_64-icu-qbittorrent-nox", I cannot understand. I am not good at this, and I googled, but find nothing. 
Can you tell me which file should downloading? PLS

**Comment by alexyw** [comment]
I test the "x86_64-qbittorrent-nox" in my computer, it seems worked well...But consider the file size difference, I don't think it is a good idea, I am confused. Should I replace it with the " x86_64-icu-qbittorrent-nox"?

**Comment by userdocs** [comment]
Either will be fine. It does not matter if it works. Non ICU is considered more default. As long as it work the either is fine.
