### ISSUE TITLE
boost build python version error

### ISSUE THREAD

**Issue by guillaumedsde** [userdocs/qbittorrent-nox-static#5]
Hi, awesome scripts you've built, I'm trying to use them to build an alpine based qbittorrent container with a statically compilled binary.
I am using [this dockerfile](https://gitlab.com/guillaumedsde/alpine-qbittorrent-openvpn/-/blob/21281649ffd0ceeb83bf575fc9bfd65778513e33/Dockerfile) (alpine 3.11 with the following build commands:

```
RUN apk add --no-cache \
    wget \
    curl \
    bash \
    bash-completion \
    build-base \
    pkgconf \
    autoconf \
    automake \
    libtool \
    git \
    perl \
    python3 \
    python3-dev \
    linux-headers 

# get qBittorrent compilation script
ADD https://git.io/JvLcZ qbittorrent-nox-static-musl.sh 

RUN chmod 700 qbittorrent-nox-static-musl.sh 

RUN ./qbittorrent-nox-static-musl.sh all --no-delete
```

but I'm struggling to get boost to build, I get this error :
```
#14 963.9 Submodule path 'tools/quickbook': checked out '944f760cc2decfe745540f019cad078a57a27337'
#14 963.9 Building Boost.Build engine with toolset gcc... tools/build/src/engine/b2
#14 973.1 Unicode/ICU support for Boost.Regex?... not found.
#14 973.1 Generating Boost.Build configuration in project-config.jam for gcc...
#14 973.2 
#14 973.2 Bootstrapping is done. To build, run:
#14 973.2 
#14 973.2     ./b2
#14 973.2     
#14 973.2 To generate header files, run:
#14 973.2 
#14 973.2     ./b2 headers
#14 973.2 
#14 973.2 To adjust configuration, edit 'project-config.jam'.
#14 973.2 Further information:
#14 973.2 
#14 973.2    - Command line help:
#14 973.2      ./b2 --help
#14 973.2      
#14 973.2    - Getting started guide: 
#14 973.2      http://www.boost.org/more/getting_started/unix-variants.html
#14 973.2      
#14 973.2    - Boost.Build documentation:
#14 973.2      http://www.boost.org/build/
#14 973.2 
#14 974.2 /root/qbittorrent-build/boost/tools/build/src/build/feature.jam:491: in feature.validate-value-string from module feature
#14 974.2 error: "3.8" is not a known value of feature <python>
#14 974.2 error: legal values:
#14 974.2 /root/qbittorrent-build/boost/tools/build/src/build/property.jam:345: in validate1 from module property
#14 974.2 /root/qbittorrent-build/boost/tools/build/src/build/property.jam:371: in property.validate from module property
#14 974.2 /root/qbittorrent-build/boost/tools/build/src/build/build-request.jam:271: in convert-command-line-element from module build-request
#14 974.2 /root/qbittorrent-build/boost/tools/build/src/build/build-request.jam:222: in build-request.convert-command-line-elements from module build-request
#14 974.2 /root/qbittorrent-build/boost/tools/build/src/build-system.jam:774: in load from module build-system
#14 974.2 /root/qbittorrent-build/boost/tools/build/src/kernel/modules.jam:295: in import from module modules
#14 974.2 /root/qbittorrent-build/boost/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
#14 974.2 /root/qbittorrent-build/boost/boost-build.jam:17: in module scope from module
#14 974.2 
```

**Comment by userdocs** [comment]
this error does not occur in a non docker setup and i could not replicate it as a issue with the script.

It appears to possibly be a environment issue with how python is detected and passed to boost.

```
#14 974.2 error: "3.8" is not a known value of feature <python>
```

Regarding this file generation command:

https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-static-musl.sh#L203

As to why, i cannot say. maybe try without `--no-delete`

**Comment by guillaumedsde** [comment]
removing `--no-delete` didn't fix it, I'm going to try and experiment with the script (specifically the line you mention) in an alpine container see if I can find the issue

**Comment by userdocs** [comment]
Run the script on alpine non docker vps and see what happens.

**Comment by guillaumedsde** [comment]
> Run the script on alpine non docker vps and see what happens.

Yep, I tested the script on a scaleway Alpine Linux `3.7.0` VPS and it worked, something's off about the docker container, I will continue investigating

**Comment by userdocs** [comment]
The jam file creation before is how I tell boost which python to use. Can you check the contents of that file on error please.

**Comment by guillaumedsde** [comment]
ah! found the issue!

https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-static-musl.sh#L203
```
[[ "$1" =~ $modules ]] && { mkdir -p "$install_dir"; echo 'using python : '"$python_short_version"' : /usr/bin/python'"$python_short_version"' : /usr/include/python'"$python_short_version"' : /usr/lib/python'"$python_short_version"' ;' > user-config.jam; }
```

creates the `user-config.jam` file (with the correct content) in the *current directory* and I was running the script from `/` as opposed to `~` should the line instead be? :

```
[[ "$1" =~ $modules ]] && { mkdir -p "$install_dir"; echo 'using python : '"$python_short_version"' : /usr/bin/python'"$python_short_version"' : /usr/include/python'"$python_short_version"' : /usr/lib/python'"$python_short_version"' ;' > $HOME/user-config.jam; }
```

**Comment by userdocs** [comment]
It would make sense. There is no reason to no have `$HOME` prefixes to that file path creation. To be honest I am not sure why it is not already there. If that fixes it i can update the scripts.

**Comment by guillaumedsde** [comment]
seems to fix it, although I'm getting another error but its probably something else (I'm looking into it):

```
#12 1030. Submodule path 'tools/quickbook': checked out '944f760cc2decfe745540f019cad078a57a27337'
#12 1030. Building Boost.Build engine with toolset gcc... tools/build/src/engine/b2
#12 1039. Unicode/ICU support for Boost.Regex?... not found.
#12 1039. Generating Boost.Build configuration in project-config.jam for gcc...
#12 1039. 
#12 1039. Bootstrapping is done. To build, run:
#12 1039. 
#12 1039.     ./b2
#12 1039.     
#12 1039. To generate header files, run:
#12 1039. 
#12 1039.     ./b2 headers
#12 1039. 
#12 1039. To adjust configuration, edit 'project-config.jam'.
#12 1039. Further information:
#12 1039. 
#12 1039.    - Command line help:
#12 1039.      ./b2 --help
#12 1039.      
#12 1039.    - Getting started guide: 
#12 1039.      http://www.boost.org/more/getting_started/unix-variants.html
#12 1039.      
#12 1039.    - Boost.Build documentation:
#12 1039.      http://www.boost.org/build/
#12 1039. 
#12 1039. ./qbittorrent-nox-static-musl.sh: line 364: /root/qbittorrent-build/bin/b2: No such file or directory
```

**Comment by guillaumedsde** [comment]
here's a PR for the fix: https://github.com/userdocs/qbittorrent-nox-static/pull/6 :)

**Comment by userdocs** [comment]
So that is this line https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-static-musl.sh#L364

Specifically this part `"$install_dir/bin/b2"` which i can see is expanded as `/root/qbittorrent-build/bin/b2`

I'd look to the previous module where boost build is created and installed. Was there an error? is it installed to the right place?

This all seems to related to environment issue specific to the docker scenario.

**Comment by guillaumedsde** [comment]
> So that is this line https://github.com/userdocs/qbittorrent-nox-static/blob/master/qbittorrent-nox-static-musl.sh#L364
> 
> Specifically this part `"$install_dir/bin/b2"` which i can see is expanded as `/root/qbittorrent-build/bin/b2`
> 
> I'd look to the previous module where boost build is created and installed. Was there an error? is it installed to the right place?
> 
> This all seems to related to environment issues specific to the docker scenario.

yep this was my fault, I was not building `all` modules just `boost` so it was failing because it needs `boost_build` to be built before

**Comment by userdocs** [comment]
To build quickly you would need to install qt and boost via apk. Otherwise it just takes a while. You would probably need alpine edge as well.

**Comment by guillaumedsde** [comment]
> To build quickly you would need to install qt and boost via apk. Otherwise it just takes a while. You would probably need alpine edge as well.

Will the final binary be fully static if I do that? I am aiming to make a [distroless](https://github.com/GoogleContainerTools/distroless) docker container in which I won't be able to install any dependencies

**Comment by userdocs** [comment]
No but perhaps I am not understanding the process. How does the end user acquire the binary. So they have to build it everytime or are you providing the binary via another medium?

**Comment by guillaumedsde** [comment]
The idea is to build a static qbittorrent binary every time qbittorrent is updated then embed that binary in a distroless docker image then publish it to the [docker hub](http://hub.docker.com/) like the [one I currently use](https://github.com/guillaumedsde/alpine-qbittorrent-openvpn) (alpine linux based, but not distroless)

**Comment by userdocs** [comment]
Then you should use the all switch per build and not skip any modules.

**Comment by guillaumedsde** [comment]
cheers, thanks for the help :)
