### ISSUE TITLE
qbittorrent-nox seedbox

### ISSUE THREAD

**Issue by misterkoko** [userdocs/qbittorrent-nox-static#51]
If the dev or anyone else could help out a bit:

I installed the latest x86_x64 static version on my seedbox slot and whenever I add multiple torrents / the DL/UL speeds get really fast it just turns off the WebUI completely (possibly due to the fact that libtorrent is single core, the thread is getting maximised due to the network saturation?)

Sometimes it even disconnects qbittorrent itself and it misses any torrents that might have been added during the downtime.

I found a different version from FeralHosting: https://www.feralhosting.com/wiki/software/qbittorrent

The version of that qbittorrent-nox is 4.1.6 and the size of it is only 10MB and it works great with no disconnecting of the WebUI or qbittorrent itself. Is there any chance you could build / or tell me how this was built, since I wasn't able to get down to 10MB with your latest x86_x64 static version even with the --strip option. I have also noticed that the 10MB version doesn't have RSS or Advanced Options, etc...

Any thoughts / ideas would be very welcome.

Cheers!

**Comment by userdocs** [comment]
it's too vague to really provide any useful insight. Feralhosting uses an older shared build. It's not static so it uses the system deps already present, which on debian will be libtorrent 1.1 branch I believe.

The script can build older combos within reason. Either to build it yourself or establish if it is an actual issue with libtorrent or qbittorrent and check the relevant repo for a related issue or create one.

**Comment by misterkoko** [comment]
It does the exact same thing on Deluge which is officialy supported. I'm guessing I can't do a shared build with this script correct? I'll try my luck and do a build with libtorrent 2.0, otherwise I'll just stick to that older shared build since it doesn't keep disconnecting the WebUI under any load.

**Comment by userdocs** [comment]
If it does the same thing with deluge 2 then the problem is with the libtorrent 1.2 branch. share vs not shared is not really relevant. You should try an older build combo using branch 1_1 or open an issue on libtorrent
