### ISSUE TITLE
Pre-built binaries: SOCKS5 proxy error

### ISSUE THREAD

**Issue by joshft91** [userdocs/qbittorrent-nox-static#52]
Hardware: Raspberry Pi 4 2GB
OS: [Raspberry Pi OS 64-bit](https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-05-28/) (Debian 10.10)

Now that binaries are being built and published with each release (which is awesome, by the way) I've encountered some interesting behavior trying to use the pre-built binaries on the hardware/software above.

Problem: After configuring qBittorrent to use a SOCKS5 proxy using any of the "pre built" `qbittorrent-nox` binaries (both libtorrent 1.x and 2.x) causes the following error: `SOCKS5 proxy error. Message: SOCKS5 error. op: hostname_lookup ec: Host not found (authoritative) ep: 0.0.0.0:40224`

I initially thought it was possibly a LibTorrent problem so I tried both versions but encountered the same behavior on any of the binaries built for each release.

What's interesting, however, is if I build the `qbittorrent-nox` binary on my Pi4 using the `qbittorrent-nox-static.sh` I'm able to produce a 4.3.6 qBittorrent-nox binary that runs and allows a proxy to be configured without issue. I'm wondering if we could possibly track down what dependency may be causing an issue between what I'm building locally and the binaries that get produced for each release.

Let me know what kind of other information may be useful and we can go from there. It would be great to get a binary built in the releases that would work from the get-go on the Raspberry Pi. Cheers.

**Comment by userdocs** [comment]
It may be that they are built on Alpine and you are seeing a glibc related issue (perhaps). You can test using these builds when they are completed

https://github.com/userdocs/qbittorrent-nox-static/actions/runs/1006206157

Test these and see. If they do not have the issue then it will be based on the glibc part that Alpine does not use.

**Comment by joshft91** [comment]
Excellent, thanks @userdocs. I'm going to have to try this out tomorrow since I didn't get a chance to get back to it this evening. I'll let you know how I turn out

**Comment by joshft91** [comment]
Had a chance to try some of these this morning. Unfortunately it looks like I'm getting the error `cannot execute binary file: Exec format error` on pretty much all of the builds above.

Running the command `file qbittorrent-nox` on the `debian-buster-RC-1-2-cmake-nox` artifact shows something like the below. Seems that it was built for an x86-64 architecture.

`qbittorrent-nox: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=30150fd4d723482ebf2235eba6c182f5acacd45e, for GNU/Linux 3.2.0, with debug_info, not stripped`

**Comment by userdocs** [comment]
yeah, slight oversight by me. This is the action that creates shared installable debs packages for debian based using multi arch.

https://github.com/userdocs/test/actions/runs/1008571196

If you can unpack and test the match your arch.

You could also install qemu static [like this](https://wiki.debian.org/QemuUserEmulation)

```
apt install qemu binfmt-support qemu-user-static 
```

And the x86_64 build should also work.

**Comment by joshft91** [comment]
Appreciate you building those. I downloaded `debian-bullseye-qbittorrent-nox-4.4.0beta1-libtorrent-2.0.4.0-arm64v8` since I think that lines up most with the Pi4 CPU architecture (`Cortex-A72 (ARM v8) 64-bit SoC`)

I downloaded the `.deb` file and unpacked it to get `/usr/local/bin/qbittorrent-nox` and attempted to execute the binary. I got this message unfortunately: `./qbittorrent-nox: error while loading shared libraries: libtorrent-rasterbar.so.2.0: cannot open shared object file: No such file or directory`

Seems like this may be an issue by building the beta/libtorrent 2.0? Is it possible to get a debian-buster along with libtorrent 1.x built to match the most stable version of qBittorrent?

**Comment by userdocs** [comment]
I think it's the paths not being relative and it is expecting them to be in locations where they would be installed to. In this case /usr/local

You can symlink the required files or install and uninstall the Deb.

**Comment by joshft91** [comment]
I ended up going back to your 2nd option above to use qemu to run the x86_64 build and qBittorrent started up and the SOCKS5 proxy worked just fine. I think that means that your original suspicion of glibc being the problem was correct. If so, is it possible to get those added as part of your release binaries? If not, no worries, glad we tracked down the issue.

**Comment by userdocs** [comment]
What I am wondering is if this is something making the assumption it is on a glibc system since qbittorrent prefers ubuntu as a OS. Apline is not specifically supported.

> Does it reproduce the same bug on Alpine OS. I'd need to use a docker and try?
> 
> Can I use the existing multiarch setup with other cross build toolkits since the framework should be pretty flexible?
> 
> Can it be addressed upstream to make dns resolution less OS specific so that the bug is fixed generally.

These are the main points that occur to me as I understand this issue.

**Comment by joshft91** [comment]
I would guess that most of the time this isn't even a problem for most people like you mentioned due to the fact that they either (a) run on an OS that works or (b) they don't even use the SOCKS5 proxy feature.

> Can I use the existing multiarch setup with other cross build toolkits since the framework should be pretty flexible?

If this is possible at all I'd be more than happy to try out any binaries that you build otherwise for now I can get along just fine since we know that I can run your script locally to get a good build.

**Comment by userdocs** [comment]
Just to come back to this, if you set the IP manually to the sock proxy IP instead of use the `0.0.0.0` does it work?

> SOCKS5 proxy error. Message: SOCKS5 error. op: hostname_lookup ec: Host not found (authoritative) ep: 0.0.0.0:40224

**Comment by joshft91** [comment]
Sorry for just getting back to you. I downloaded the armv7-qbittorrent-nox binary and ran it and noticed the same issue as before. That was using the hostname of the SOCKS5 proxy.

However, after pinging the hostname and getting and IP and using that in the `host` field, the proxy worked fine.

**Comment by userdocs** [comment]
After reading this https://wiki.musl-libc.org/functional-differences-from-glibc.html#Name-Resolver/DNS I think using the full IP will always work unless you are willing to edit your hosts/resolve.conf files.

I think just using the IP is the easiest option and requires no systems changes,

**Comment by joshft91** [comment]
Yeah, it must be something with the hostname resolution. The only reason I opened the issue was because I could build the binary fine on my Pi4 locally and have the hostname work. 

Thanks for looking into this - will close.
