### ISSUE TITLE
are there hard coded options?

### ISSUE THREAD

**Issue by mgaulton** [userdocs/qbittorrent-nox-static#55]
I love the app, fixes the issues I have on Opensuse with the repo versions but I've noticed something odd.
with normal version when it worked, I could bump up connections and slots and it would reflect in the queue.
with this version, i've noticed that with the same config or even making the values different, it only seems to use 10 queue slots, no matter what the value is.
It does this consistently, even after updating the built binary or restarting or anything.
Just curious, why this might be the case?

**Comment by userdocs** [comment]
I don't hardcode, change or modify any settings with these builds. There is no customisation outside of the build process itself. 

I would say check the settings file/folder is writable for the app as that is what your problems sounds like. A permissions issue.

**Comment by mgaulton** [comment]
OK, I only noticed it since the switch so I just wanted to verify. Thank you kindly.

**Comment by mgaulton** [comment]
OH, and the folders are owned by the isolation user, and it has the updated values in the conf, it just wasn't reflected in the queue activity the way I expected.

**Comment by userdocs** [comment]
I cannot say for sure it's not a bug. usually building on the platform would confirm if it is a bug or not. This should be pretty adaptable to your OS

**Comment by mgaulton** [comment]
awesome thanks. I'll look at it

**Comment by userdocs** [comment]
It the basics of building libtorrent and qbit but probably also needs a supported version of qt to go with it. so 5.12 onwards. If you can't build try the discussions on the qbit repo to see if that can narrow it down.

https://github.com/qbittorrent/qBittorrent/discussions

Also the logs might help?
