### ISSUE TITLE
error: unknown option `sort=-v:refname'

### ISSUE THREAD

**Issue by ronioncloud** [userdocs/qbittorrent-nox-static#56]
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

✔ Dependencies installed!

 ● All checks passed and core dependencies are installed, continuing to build
error: unknown option `sort=-v:refname'
usage: git ls-remote [--heads] [--tags] [--refs] [--upload-pack=<exec>]
                     [-q | --quiet] [--exit-code] [--get-url]
                     [--symref] [<repository> [<refs>...]]

    -q, --quiet           do not print remote URL
    --upload-pack <exec>  path of git-upload-pack on the remote host
    -t, --tags            limit to tags
    -h, --heads           limit to heads
    --refs                do not show peeled tags
    --get-url             take url.<base>.insteadOf into account
    --exit-code           exit with exit code 2 if no matching refs are found
    --symref              show underlying ref in addition to the object pointed by it

**error: unknown option `sort=-v:refname**'
usage: git ls-remote [--heads] [--tags] [--refs] [--upload-pack=<exec>]
                     [-q | --quiet] [--exit-code] [--get-url]
                     [--symref] [<repository> [<refs>...]]

    -q, --quiet           do not print remote URL
    --upload-pack <exec>  path of git-upload-pack on the remote host
    -t, --tags            limit to tags
    -h, --heads           limit to heads
    --refs                do not show peeled tags
    --get-url             take url.<base>.insteadOf into account
    --exit-code           exit with exit code 2 if no matching refs are found
    --symref              show underlying ref in addition to the object pointed by it

 ● One or more of the provided modules are not supported

 ● Below is a list of supported modules

 ● all bison gawk glibc zlib iconv openssl boost libtorrent qtbase qttools qbittorrent

**Comment by userdocs** [comment]
Your version of git is too old. Install a newer version and it will work.

**Comment by userdocs** [comment]
It should be fixed with this.

https://github.com/userdocs/qbittorrent-nox-static/commit/c9fd61b6a4fe3218543e1b14c8bd177dbb367ba3
