### ISSUE TITLE
Truble with archetecture 'aarch64-linux-musl failed'

### ISSUE THREAD

**Issue by Deema35** [userdocs/qbittorrent-nox-static#59]
Hi. I try compile qbittorrent static manually. But i'm stuck on iconv.

```
./configure --host=aarch64-linux-musl --prefix=/home/dmitriy/MyProk/qtdir/qbtbuild --disable-shared --enable-static
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for aarch64-linux-musl-strip... no
checking for strip... strip
checking whether make sets $(MAKE)... (cached) yes
checking for aarch64-linux-musl-gcc... no
checking for gcc... gcc
checking for C compiler default output... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking how to run the C preprocessor... gcc -E
checking for egrep... grep -E
checking whether gcc needs -traditional... no
checking for a BSD-compatible install... /usr/bin/install -c
checking build system type... x86_64-unknown-linux-gnu
checking host system type... Invalid configuration `aarch64-linux-musl': machine `aarch64-linux' not recognized
configure: error: /bin/bash autoconf/config.sub aarch64-linux-musl failed
```
I had set env variable:
```
CHOST=aarch64-linux-musl
CC=aarch64-linux-musl-gcc
AR=aarch64-linux-musl-ar
CXX=aarch64-linux-musl-g++
PKG_CONFIG_PATH=/home/dmitriy/MyProk/qtdir/qbtbuild/lib/pkgconfig
LOCAL_USER_HOME="${HOME}"
PATH="/home/dmitriy/MyProk/qtdir/qbtbuild/bin${PATH:+:"$PATH"}"
LD_LIBRARY_PATH=-L/home/dmitriy/MyProk/qtdir/qbtbuild/lib
```
I had examined your's script but don't understand how you set cross toolchain part.

**Comment by userdocs** [comment]
First thing is that ICU is not actually required. You can skip this if want and stick with iconv.

And iconv is not actually a libtorrent v2 requirement anymore, just for v1

ICU is not a requirement of anything except QT

I can help with the script behaviour but you can skip ICU if you want.

**Comment by Deema35** [comment]
Yes I skip ICU and  iconv but I cann't build OpenSSL. Though I set aarch64,
 `./Configure "linux-aarch64" --prefix=/home/dmitriy/MyProk/qtdir/qbtbuild --openssldir="/etc/ssl" threads no-shared no-dso no-comp`
It anyway use toolchain from /usr/bin not cross toolchain. And I want understand how you set PATH to cross toolchain in your script because I can't figure out it.
 I don't use script deliberately, because I want to learn how use cross compail.

**Comment by userdocs** [comment]
It looks like you don't have the required cross build toolchain. 

I use Alpine linux and these pre built toolchains https://musl.cc - here is an example of how you use it https://ariya.io/2020/06/cross-compiling-with-musl-toolchains

You can also use these. https://toolchains.bootlin.com

Download the one you want, extract it and then set the paths to that binary

`CHOST=/path/to/extracted/aarch64-linux-musl`

**Comment by Deema35** [comment]
Thank you it's will help.

**Comment by userdocs** [comment]
Closing this as it's not an issue with the script.

Please use the discussions feature for non issue stuff please.
