### ISSUE TITLE
hi how can i use it on my router

### ISSUE THREAD

**Issue by wei134102** [userdocs/qbittorrent-nox-static#72]
i am chinese ,and my english is poor ,blew error happen on my router
my quesion is how can i use or rebuild it. thinks(i have a pc with ubuntu 18.04 64  bit)

root@XiaoQiang:/userdisk/opt/bin# qbittorrent-nox 
Illegal instruction (core dumped)
root@XiaoQiang:/userdisk/opt/bin# uname -a
Linux XiaoQiang 2.6.36 #3 MiWiFi-R1D-2.25.213 SMP PREEMPT Tue Oct 16 11:44:14 UTC 2018 armv7l GNU/Linux
root@XiaoQiang:/userdisk/opt/bin# 

root@XiaoQiang:/# cat /proc/cpuinfo 
Processor       : ARMv7 Processor rev 0 (v7l)
processor       : 0
BogoMIPS        : 1998.84

processor       : 1
BogoMIPS        : 1998.84

Features        : swp half thumb fastmult edsp 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : Northstar Prototype
Revision        : 0000
Serial          : 0000000000000000

b_chip  : 53010
b_chiprev       : 0
b_chippkg       : 0

**Comment by userdocs** [comment]
`Illegal instruction (core dumped)` usually means using x64 on x86.

Make sure you download the armv7 build

**Comment by wei134102** [comment]
> `Illegal instruction (core dumped)` usually means using x64 on x86.
> 
> Make sure you download the armv7 build

yes i am sure,i want rebuild it, how can i do ,anyone can help me?there many users(miwifi r1d )in china ,transmission can be usered on my router,but i like qbittorrent.

**Comment by userdocs** [comment]
Use the right download?

https://github.com/userdocs/qbittorrent-nox-static/latest/releases/download/armv7-qbittorrent-nox

**Comment by wei134102** [comment]
> Use the right download?
> 
> https://github.com/userdocs/qbittorrent-nox-static/latest/releases/download/armv7-qbittorrent-nox

我已经服了，我关闭了好吧！I have served it, I closed it all right!

**Comment by userdocs** [comment]
It worked?

Fixed?

**Comment by wei134102** [comment]
不，不，没有冒犯的意思，但是你的回答使我看起来像个傻子！No, no, no offense, but your answer makes me look like a fool!

**Comment by userdocs** [comment]
Unless you can communicate the issue better there is not much I can do to help as I don't really understand.
 
I can say read the English only docs https://userdocs.github.io/qbittorrent-nox-static/#/script-installation ?

Maybe try this https://github.com/c0re100/qBittorrent-Enhanced-Edition/releases
