### ISSUE TITLE
There is a minimum announce time of 30 seconds!

### ISSUE THREAD

**Issue by cheungchingli** [userdocs/qbittorrent-nox-static#80]
![image](https://user-images.githubusercontent.com/25190239/158057096-4f887eca-b4d1-4bab-8292-5e6f33f767af.png)

**Comment by userdocs** [comment]
I don't modify settings. You should ask here

https://github.com/qbittorrent/qBittorrent/discussions

Or maybe here they might know more?

https://github.com/c0re100/qBittorrent-Enhanced-Edition/discussions
