### ISSUE TITLE
QtLockedFile::lock(): file is not opened

### ISSUE THREAD

**Issue by andoruB** [userdocs/qbittorrent-nox-static#81]
Getting this output when trying to run one of your static precompiled executables:

```
./qbittorrent-nox 
QtLockedFile::lock(): file is not opened

*** Legal Notice ***
qBittorrent is a file sharing program. When you run a torrent, its data will be made available to others by means of upload. Any content you share is your sole responsibility.

No further notices will be issued.

Press 'y' key to accept and continue...
y
QtLockedFile::lock(): file is not opened
QtLockedFile::lock(): file is not opened
```

Doesn't seem to detect the settings folder/files already existing under my user's home folder, seems to start from scratch.
Any ideas what could cause this?

**Comment by userdocs** [comment]
When you say start from scratch? is it creating the settings somewhere else? I think the default location is here,

`~/.config/qBittorrent`

**Comment by andoruB** [comment]
I don't think it's creating any settings files anywhere.
I just judge that based off the repeated legal notice I get, which one would only get when they would start qBittorrent for the first time.

**Comment by userdocs** [comment]
Which would suggest the most likely cause is your settings are in the wrong place?

If you only get the prompt once then those new settings are being created and save.

You really have to provide more detail or I have to assume things about what's happening.

**Comment by andoruB** [comment]
The settings are present under ~/.config/qBittorrent as you suggested earlier.
They are properly loaded by the normal qBittorrent instance. Are the config files incompatible between this static version and the normal one?
