### ISSUE TITLE
Log spammed by `Numeric mode unsupported in the posix collation implementation` since 4.4.0

### ISSUE THREAD

**Issue by foux** [userdocs/qbittorrent-nox-static#85]
Hi!

Since the infamous qbit 4.4.0, the logs of qbit-nox are being spammed by this line : 

```
Numeric mode unsupported in the posix collation implementation
```

It can be once every few hours, or a few thousands times per minutes.

According to [this post](https://forum.qt.io/topic/102262/unsupported-in-the-posix-collation-implementation), it's due to `libicu-dev` not being installed before `Qt` when building.

Would it be possible to change the build process?

Thanks!

**Comment by Davo1624** [comment]
Can confirm this is happening as well. I can run qbit 4.3.9 and all is fine, but using the same config dir/files and upgrading to 4.4.x results in my qbittorrent container log being filled with the line listed by foux

**Comment by userdocs** [comment]
Each build has a with ICU and without variant.

Does this happen with the ICU one?

**Comment by martadinata666** [comment]
So in my log is 
```
qbittorrent_app.1.46ssic84okok@homelab    | 
qbittorrent_app.1.46ssic84okok@homelab    | ******** Information ********
qbittorrent_app.1.46ssic84okok@homelab    | To control qBittorrent, access the WebUI at: http://localhost:8090
qbittorrent_app.1.46ssic84okok@homelab    | Case insensitive sorting unsupported in the posix collation implementation
qbittorrent_app.1.46ssic84okok@homelab    | Numeric mode unsupported in the posix collation implementation
qbittorrent_app.1.46ssic84okok@homelab    | Numeric mode unsupported in the posix collation implementation
```
And the rest `Numeric bla2`. This is 4.4.2 libtorr 1.2 without `icu`. Will confirm the ICU build later.

**Comment by userdocs** [comment]
to me, the lack of ICU just means slightly faster build times and smaller binary but since the build are precompiled I might make future releases 

cmake + icu only as qt5 support is going to be dropped, maybe, with 4.5 onwards.

**Comment by userdocs** [comment]
is this resolved?

**Comment by userdocs** [comment]
I assume this fixed it so i will plan to just release ICU builds in the future.
