### ISSUE TITLE
Error(?) messages when running

### ISSUE THREAD

**Issue by Redst0neFlux** [userdocs/qbittorrent-nox-static#89]
I am running on a Raspberry Pi 400, armv7l qbittorrent-nox version 4.2.5
When I run the armv7-qbittorrent-nox file, I get these lines repeated as it starts:
> Only C and default locale supported with the posix collation implementation
> Numeric mode unsupported in the posix collation implementation

These continue to appear as the program runs.
Are these errors or should I ignore them?

**Comment by Redst0neFlux** [comment]
It appears to freeze whenever I try to move or recheck a torrent, though I am unsure if this is related. When frozen, the information window on the bottom half of the screen stops updating, and doesn't change when I select a different torrent. I may be able to upload a screen recording tomorrow if that would help.

**Comment by userdocs** [comment]
This appears a duplicate of this. https://github.com/userdocs/qbittorrent-nox-static/issues/85

Try the ICU build and see if that solves it.

**Comment by Redst0neFlux** [comment]
works, thanks :D
