### ISSUE TITLE
keep qbittorrent-nox-static up-to-date

### ISSUE THREAD

**Issue by BulldozerPete** [userdocs/qbittorrent-nox-static#91]
Hello,

is there an easy way to check for updates of qbittorrent-nox-static, download and run them?

**Comment by userdocs** [comment]
These urls will always get you the latest version

https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/x86_64-qbittorrent-nox
https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/armhf-qbittorrent-nox
https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/armv7-qbittorrent-nox
https://github.com/userdocs/qbittorrent-nox-static/releases/latest/download/aarch64-qbittorrent-nox

So the best thing is to watch the repo for new releases, but the download URL will not need to change.

**Comment by BulldozerPete** [comment]
Thx.
Is there a repository planned? That would be great for Debian.

The Docker Container mentioned in your documentation could be also very handy.
But I am missing the simple commands to pull and run the container.
