### ISSUE TITLE
Aarch64 high virtual memory usage

### ISSUE THREAD

**Issue by ProKn1fe** [userdocs/qbittorrent-nox-static#92]
Is this virtual memory usage are normal?
System: openwrt builded from source
Device: NanoPI R4S
Using this binary - https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-4.4.2_v2.0.6/aarch64-qbittorrent-nox
![image](https://user-images.githubusercontent.com/54151358/168074182-827ea59c-d4d5-4a57-a07f-0bd4aca3eb96.png)
![image](https://user-images.githubusercontent.com/54151358/168074347-e32d1f60-1253-4897-93cf-b3d053b3b770.png)
qBittorent.conf
`
[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AnnounceToAllTrackers=true
Session\AsyncIOThreadsCount=2
Session\BandwidthSchedulerEnabled=true
Session\BlockPeersOnPrivilegedPorts=true
Session\CheckingMemUsageSize=256
Session\CoalesceReadWrite=true
Session\ConnectionSpeed=8
Session\DHTEnabled=true
Session\FilePoolSize=256
Session\GlobalUPSpeedLimit=0
Session\IgnoreLimitsOnLAN=true
Session\Interface=pppoe-wan
Session\InterfaceName=pppoe-wan
Session\MaxConnections=1024
Session\MaxConnectionsPerTorrent=512
Session\MaxUploads=256
Session\MaxUploadsPerTorrent=128
Session\MultiConnectionsPerIp=true
Session\QueueingSystemEnabled=false
Session\ReannounceWhenAddressChanged=true
Session\SendBufferLowWatermark=32
Session\SendBufferWatermark=1024
Session\UseAlternativeGlobalSpeedLimit=true
Session\UseOSCache=true
Session\uTPRateLimited=false

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=3

[Preferences]
Advanced\RecheckOnCompletion=false
Advanced\trackerPort=9000
Connection\ResolvePeerCountries=true
DynDNS\DomainName=changeme.dyndns.org
DynDNS\Enabled=false
DynDNS\Password=
DynDNS\Service=DynDNS
DynDNS\Username=
General\Locale=ru_RU
MailNotification\email=
MailNotification\enabled=false
MailNotification\password=
MailNotification\req_auth=true
MailNotification\req_ssl=false
MailNotification\sender=qBittorrent_notification@example.com
MailNotification\smtp_server=smtp.changeme.com
MailNotification\username=
Scheduler\days=EveryDay
Scheduler\end_time=@Variant(\0\0\0\xf\x5%q\xa0)
Scheduler\start_time=@Variant(\0\0\0\xf\x1\xb7t\0)
WebUI\AlternativeUIEnabled=false
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\BanDuration=3600
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\CustomHTTPHeaders=
WebUI\CustomHTTPHeadersEnabled=false
WebUI\HTTPS\CertificatePath=
WebUI\HTTPS\Enabled=false
WebUI\HTTPS\KeyPath=
WebUI\HostHeaderValidation=true
WebUI\LocalHostAuth=true
WebUI\MaxAuthenticationFailCount=5
WebUI\Port=8080
WebUI\ReverseProxySupportEnabled=false
WebUI\RootFolder=
WebUI\SecureCookie=true
WebUI\ServerDomains=*
WebUI\SessionTimeout=3600
WebUI\TrustedReverseProxiesList=
WebUI\UseUPnP=false

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
`

**Comment by userdocs** [comment]
It generally depends how many active torrents you have in that instance but qbittorrent is known for using memory and if you have a lot of torrents 2-4 gig for that instance is very plausible. This is a qbittorrent thing and not specific to this build.

You can look at advanced qbittorrent/libtorrent settings to see if you have the optimum settings for limited resources.

Being fully a static bin you load more to memory when you have an instance running than might show when using shared but since the whole thing is in memory it should perform better, for that memory usage trade off.

So the project it not specifically targeting efficient resource usage on platforms with limited ram available and the settings are all default. The static bins are just a convenient way to use current versions of the program on platforms it is otherwise unavailable on.

You may need to tweak settings to lower performance for more efficient resource usage, for example, https://www.reddit.com/r/qBittorrent/comments/s6ea1k/qbittorent_is_using_all_the_ram_cache_off/

If none of that works i'd suggest this static build of rtorrent that will work with his flood project.

https://github.com/jesec/rtorrent/releases/tag/v0.9.8-r16

You may find that is less of a memory problem.

**Comment by ProKn1fe** [comment]
I'm trying binary with [libtorrent 1.2.16](https://github.com/userdocs/qbittorrent-nox-static/releases/tag/release-4.4.2_v1.2.16) and seems it helped partially. No more 350gb virt memory in top, but luci and free say what all bad. Very interesting.

It's not a memory usage problem because there is only ~512mb really used and it does not prevent the device from working in any way. it's just weird that 10 seconds after startup it starts using 100+gb of virtual memory.

[libtorrent 2.0.6](https://github.com/userdocs/qbittorrent-nox-static/releases/tag/release-4.4.2_v2.0.6)
![image](https://user-images.githubusercontent.com/54151358/168088953-72519503-74e4-465f-8b52-c2ec1ec08e77.png)

[libtorrent 1.2.16](https://github.com/userdocs/qbittorrent-nox-static/releases/tag/release-4.4.2_v1.2.16)
![image](https://user-images.githubusercontent.com/54151358/168089723-2912c12f-1931-4c66-aab4-21b8776ca186.png)

Before qbittorent i'm trying to use transmisson from openwrt modules repository and it have absolutely same thing with virt memory usage. On transimmion forum was written what it only aarch64 related problem.
echo 1 > /proc/sys/vm/drop_caches helped clear cache but only for 1-2 min before he it gets clogged again.

**Comment by ProKn1fe** [comment]
After some research i figure what memory continue leak even after qbittorrent closed. And problem is in ntfs-3g and memory leaks going when io operation comes. I replace ntfs with ext4 on usb hdd drive and seems it fix my problem.

**Comment by userdocs** [comment]
Interesting to know. If you need to test other build combinations you can fork the repo and use this

https://github.com/userdocs/qbittorrent-nox-static/blob/master/.github/workflows/matrix_multi_build_and_release_customs_tags.yml

To make releases of custom builds to see if they help troubleshoot.

**Comment by ProKn1fe** [comment]
There is no problem with qbittorrent. All issue in what i'm use hdd with usb adapter and it's normal behavior (ext4 or ntfs without a difference).
