### ISSUE TITLE
Torrents with errors don't appear on the error section

### ISSUE THREAD

**Issue by AbuShu** [userdocs/qbittorrent-nox-static#93]
I use  [qBittorrent-nox WebUI](https://github.com/userdocs/qbittorrent-nox-static/releases/tag/release-4.4.2_v2.0.5) on a seedbox, and I'm having some issues. I'm a private trackers user.

Sometimes, torrents get deleted on private trackers, and so I want to delete them from the WebUI cuz they're no longer registered torrents, they're just a waste of space.

When I use deluge, I see all errored torrents on the error tab/section and can delete them all at once, However, on qBittorrent, they don't appear. And so I have to go manually search for each and every torrent in order to delete it, amongst 2800 seeded torrents! That's so time consuming honestly.

Why not all errored torrents appear on the error tab on the left?

**Comment by johnyb0y** [comment]
You should ask your question in the official channels of the qbittorrent project, like the [offical forum](https://qbforums.shiki.hu/). Your question is not relevant to this Github project.

**Comment by AbuShu** [comment]
> You should ask your question in the official channels of the qbittorrent project, like the [offical forum](https://qbforums.shiki.hu/). Your question is not relevant to this Github project.

Alright. Gonna close this issue then.
