### ISSUE TITLE
Change 8080 port

### ISSUE THREAD

**Issue by Argon-D** [userdocs/qbittorrent-nox-static#94]
hello , I need to run 2 qbittorrent-nox at the same time on the same machine, but on the second one I got address already in use port 8080. 
Anyone know how to edit for example to 8081? or any different?
Thanks!

**Comment by martadinata666** [comment]
use `--webui-port=xxxx`

**Comment by userdocs** [comment]
The docs covers how to run a second instance ( or any number of new instances

https://userdocs.github.io/qbittorrent-nox-static/#/install-qbittorrent?id=configuring-qbittorrent

https://userdocs.github.io/qbittorrent-nox-static/#/install-qbittorrent?id=second-instance

You run it and point to a new config and then use whatever settings you need in that.

**Comment by Argon-D** [comment]
Thanks so much guys! I mixed both answers :)

**Comment by userdocs** [comment]
can this be closed?

If you need to ask more use the discussions

https://github.com/userdocs/qbittorrent-nox-static/discussions
